// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// opt_ac
arma::vec opt_ac(const arma::vec& a_old, const arma::vec& c_old, const arma::mat& bs, const arma::mat& bs_der, const arma::vec& A, const arma::mat& X, const arma::vec& delta, const arma::vec& tobs);
RcppExport SEXP test_opt_ac(SEXP a_oldSEXP, SEXP c_oldSEXP, SEXP bsSEXP, SEXP bs_derSEXP, SEXP ASEXP, SEXP XSEXP, SEXP deltaSEXP, SEXP tobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type a_old(a_oldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_old(c_oldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs_der(bs_derSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tobs(tobsSEXP);
    __result = Rcpp::wrap(opt_ac(a_old, c_old, bs, bs_der, A, X, delta, tobs));
    return __result;
END_RCPP
}
// opt_b
arma::vec opt_b(const arma::vec& a_new, const arma::vec& b_old, const arma::vec& c_new, const arma::mat& bs, const arma::mat& bs_der_all, const arma::vec& A, const arma::mat& X, const arma::vec& delta, const arma::vec& tobs);
RcppExport SEXP test_opt_b(SEXP a_newSEXP, SEXP b_oldSEXP, SEXP c_newSEXP, SEXP bsSEXP, SEXP bs_der_allSEXP, SEXP ASEXP, SEXP XSEXP, SEXP deltaSEXP, SEXP tobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type a_new(a_newSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_old(b_oldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_new(c_newSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs_der_all(bs_der_allSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tobs(tobsSEXP);
    __result = Rcpp::wrap(opt_b(a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs));
    return __result;
END_RCPP
}
// likeli
double likeli(const arma::vec& a, const arma::vec& b, const arma::vec& c, const arma::vec& A, const arma::mat& X, const arma::vec& delta, const arma::vec& tobs, const arma::vec& knots, int order);
RcppExport SEXP test_likeli(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP ASEXP, SEXP XSEXP, SEXP deltaSEXP, SEXP tobsSEXP, SEXP knotsSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tobs(tobsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(likeli(a, b, c, A, X, delta, tobs, knots, order));
    return __result;
END_RCPP
}
// solvealg
SEXP solvealg(arma::mat X, arma::mat X_inquantile, arma::vec t_obs, arma::vec censoring, arma::vec A, int k, int max_n, int fix_beta);
RcppExport SEXP test_solvealg(SEXP XSEXP, SEXP X_inquantileSEXP, SEXP t_obsSEXP, SEXP censoringSEXP, SEXP ASEXP, SEXP kSEXP, SEXP max_nSEXP, SEXP fix_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_inquantile(X_inquantileSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_obs(t_obsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censoring(censoringSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type max_n(max_nSEXP);
    Rcpp::traits::input_parameter< int >::type fix_beta(fix_betaSEXP);
    __result = Rcpp::wrap(solvealg(X, X_inquantile, t_obs, censoring, A, k, max_n, fix_beta));
    return __result;
END_RCPP
}
// test_splines
SEXP test_splines(arma::mat X, arma::mat X_inquantile, arma::vec beta, arma::vec knots, int dev, int order, int k);
RcppExport SEXP test_test_splines(SEXP XSEXP, SEXP X_inquantileSEXP, SEXP betaSEXP, SEXP knotsSEXP, SEXP devSEXP, SEXP orderSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_inquantile(X_inquantileSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< int >::type dev(devSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    __result = Rcpp::wrap(test_splines(X, X_inquantile, beta, knots, dev, order, k));
    return __result;
END_RCPP
}
// opt_ac_test
SEXP opt_ac_test(const arma::vec& a_old, const arma::vec& c_old, const arma::mat& bs, const arma::mat& bs_der, const arma::vec& A, const arma::mat& X, const arma::vec& delta, const arma::vec& tobs);
RcppExport SEXP test_opt_ac_test(SEXP a_oldSEXP, SEXP c_oldSEXP, SEXP bsSEXP, SEXP bs_derSEXP, SEXP ASEXP, SEXP XSEXP, SEXP deltaSEXP, SEXP tobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type a_old(a_oldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_old(c_oldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs_der(bs_derSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tobs(tobsSEXP);
    __result = Rcpp::wrap(opt_ac_test(a_old, c_old, bs, bs_der, A, X, delta, tobs));
    return __result;
END_RCPP
}
// opt_b_test
SEXP opt_b_test(const arma::vec& a_new, const arma::vec& b_old, const arma::vec& c_new, const arma::mat& bs, const arma::mat& bs_der_all, const arma::vec& A, const arma::mat& X, const arma::vec& delta, const arma::vec& tobs);
RcppExport SEXP test_opt_b_test(SEXP a_newSEXP, SEXP b_oldSEXP, SEXP c_newSEXP, SEXP bsSEXP, SEXP bs_der_allSEXP, SEXP ASEXP, SEXP XSEXP, SEXP deltaSEXP, SEXP tobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type a_new(a_newSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_old(b_oldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_new(c_newSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs_der_all(bs_der_allSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tobs(tobsSEXP);
    __result = Rcpp::wrap(opt_b_test(a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs));
    return __result;
END_RCPP
}
// opt_b_QP
arma::vec opt_b_QP(const arma::vec& a_new, const arma::vec& b_old, const arma::vec& c_new, const arma::mat& bs, const arma::mat& bs_der_all, const arma::vec& A, const arma::mat& X, const arma::vec& delta, const arma::vec& tobs);
RcppExport SEXP test_opt_b_QP(SEXP a_newSEXP, SEXP b_oldSEXP, SEXP c_newSEXP, SEXP bsSEXP, SEXP bs_der_allSEXP, SEXP ASEXP, SEXP XSEXP, SEXP deltaSEXP, SEXP tobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type a_new(a_newSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_old(b_oldSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_new(c_newSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bs_der_all(bs_der_allSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tobs(tobsSEXP);
    __result = Rcpp::wrap(opt_b_QP(a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs));
    return __result;
END_RCPP
}
