# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opt_ac <- function(a_old, c_old, bs, bs_der, A, X, delta, tobs, stable) {
    .Call('test_opt_ac', PACKAGE = 'test', a_old, c_old, bs, bs_der, A, X, delta, tobs, stable)
}

opt_b <- function(a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs) {
    .Call('test_opt_b', PACKAGE = 'test', a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs)
}

likeli <- function(a, b, c, A, X, delta, tobs, knots, order) {
    .Call('test_likeli', PACKAGE = 'test', a, b, c, A, X, delta, tobs, knots, order)
}

cal_knots <- function(X_inquantile, b_new, X, k, order, k_knots, bs, bs_der, bs_der_all) {
    invisible(.Call('test_cal_knots', PACKAGE = 'test', X_inquantile, b_new, X, k, order, k_knots, bs, bs_der, bs_der_all))
}

solvealg <- function(X, X_inquantile, t_obs, censoring, A, k, max_n, fix_beta, stable) {
    .Call('test_solvealg', PACKAGE = 'test', X, X_inquantile, t_obs, censoring, A, k, max_n, fix_beta, stable)
}

test_splines <- function(X, X_inquantile, beta, knots, dev, order, k) {
    .Call('test_test_splines', PACKAGE = 'test', X, X_inquantile, beta, knots, dev, order, k)
}

opt_ac_test <- function(a_old, c_old, bs, bs_der, A, X, delta, tobs, stable) {
    .Call('test_opt_ac_test', PACKAGE = 'test', a_old, c_old, bs, bs_der, A, X, delta, tobs, stable)
}

opt_b_test <- function(a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs) {
    .Call('test_opt_b_test', PACKAGE = 'test', a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs)
}

opt_b_QP <- function(a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs) {
    .Call('test_opt_b_QP', PACKAGE = 'test', a_new, b_old, c_new, bs, bs_der_all, A, X, delta, tobs)
}

